### PR TITLE
roundup-demo fixes

### PR DESCRIPTION
**Pull request by jerrykan**
A couple of small fixes to improve the user's experience when using `roundup-demo`.

My `git-remote-hg` setup is currently broken some I'm unable to push directly to the SourceForge Mercurial repo. So I'm creating a pull request so either I remember to merge this fixes when I get `git-remote-hg` working, or someone else merges them and pushes them to SourceForge.

### CODE REVIEW

**Comment by rouilj** [comment]
Hi John:

In message <roundup-tracker/roundup/pull/2@github.com>,
John Kristensen writes:
>A couple of small fixes to improve the user's experience when
>using `roundup-demo`.
>
>My `git-remote-hg` setup is currently broken some I'm unable to push
>directly to the SourceForge Mercurial repo. So I'm creating a pull
>request so either I remember to merge this fixes when I get
>`git-remote-hg` working, or someone else merges them and pushes them
>to SourceForge.

The emailed version of the codecov report for this pull shows a drop
of 0.5% in overall coverage. But the one on this pull request shows
0.01%. The email report shows less coverage for files your patch
didn't change. I assume this means your repo is behind the head
revision of mercurial and thus missing tests??

It's wierd that the online report codecov appended to the pull reports
differently from the emailed report though.

Also do you have any ideas on running demo.py as part of the tests?
At the very least it would probably be good to fire up demo.py with
the anydbm backend and each template. That should have caught each of
the problems your fixing. Thoughts?

--
				-- rouilj
John Rouillard
===========================================================================
My employers don't acknowledge my existence much less my opinions.

**Comment by rouilj** [comment]
Also John, I don't think you need:

  Add `realname` attribute to `user` in `minimal` template schema

in demo.py is this bit of code:

```
    # FIXME: Move tracker-specific demo initialization into the tracker
    # templates.
    if template == 'minimal':
        db.user.create(username='demo', password=password.Password('demo'),
                       roles='User')
    else:
        db.user.create(username='demo', password=password.Password('demo'),
                       realname='Demo User', roles='User')
```
whish should not try initializing the realname property if using the minimal template. Maybe the bug that needs
to be fixed is that template == 'minimal' is not true for the minimal template???

**Comment by jerrykan** [comment]
> whish should not try initializing the realname property if using the minimal template. Maybe the bug that needs
> to be fixed is that template == 'minimal' is not true for the minimal template???

It seems that [`def install_demo(home, backend, template)`](https://github.com/roundup-tracker/roundup/blob/master/roundup/demo.py#L26) may have two different types of string value depending on where it is invoked from.

When invoked from [`roundup/scripts/roundup_demo.py](https://github.com/roundup-tracker/roundup/blob/master/roundup/scripts/roundup_demo.py#L59) (ie. by running `roundup-demo`) the `install_demo()` function is passed a `template` value that is the full path to the template directory. In this case the `template == 'minimal'` won't match and will result in an Exception.

When invoked from [`roundup/demo.py`](https://github.com/roundup-tracker/roundup/blob/master/roundup/demo.py#L206) (ie. by running `demo.py`) the `install_demo()` function is passed a `template` value that is just the name of the template. In this case the `template == 'minimal'` will match the `template == 'minimal'` condition and work as expected.

I should also note that `install_demo()` makes some assumptions about he location of the templates, so running `demo.py` doesn't work unless your working directory is the same as where the `demo.py` script is located. On the other hand `round-admin` works correctly when run from any working directory.

**Comment by rouilj** [comment]
Ah thanks for tracking that down. I didn't even realize there was a roundup-demo to tell the truth. I wonder what the use
case for that is. I guess is allows a roundup demo for roundup installed via  an OS package?

What do you think about fixing `template == 'minimal'` check so that it strips the path from template (`os.path.basename(template)`) and only compares the last component. That should fix the roundup-demo
case when used with the installed version of the distributed minimal template.

I am ok with requiring the current working directory be the same directory where demo.py is located. IIRC all of our
docs have that assumption as well.

Thoughts?

**Comment by jerrykan** [comment]
> Ah thanks for tracking that down. I didn't even realize there was a roundup-demo to tell the truth. I wonder what the use
> case for that is. I guess is allows a roundup demo for roundup installed via an OS package?

Using `roundup-demo` is the easiest (only?) way to init a demo instance after doing a `pip install roundup`. Given that `pip` is the standard way to install python packages maybe we should be optimising for that use-case, instead of requiring user to checkout the source code to run `demo.py`?

**Comment by jerrykan** [comment]
Maybe we should move the discussion about the demo stuff to the mailing list? I didn't mean to subvert other communication channels by opening a "placeholder" pull request :D

**Comment by jerrykan** [comment]
Discussion moved to the mailing list: https://sourceforge.net/p/roundup/mailman/message/37240835/

**Comment by jerrykan** [comment]
Just adding a note here for when work on these patched get picked-up and work on again. It might be work looking at using the [setuptools `ResourceManager API`](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#resourcemanager-api) as a more portable/reliable way to accessing template files.

**Comment by rouilj** [comment]
Committed in http://sourceforge.net/p/roundup/code/ci/5a3a386aa8e7

Regarding ResourceTools, I guess I am too dumb to see how that helps deal with the man page, template dir, locale file resources.

**Pull request closed without merging**
